branches:
    only:
        - master
        - canary

before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn --ignore-engines
os: linux

language: node_js
node_js: "12"
dist: bionic

cache:
    yarn: true
    directories:
        - node_modules

matrix:
    include:
        - name: "Install dependencies"
          script: npm i

        - name: "Semantic release"
          script: npx semantic-release
