name: Release

on:
    push:
        branches:
            - master
            - beta
            - dev
            - canary
            - next

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - run: yarn
            - run: yarn semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
